#!/bin/sh

# Quick start-stop-daemon example, derived from Debian /etc/init.d/ssh
set -e

# Must be a valid filename
NAME=indigo-reposync
PIDFILE=/var/run/$NAME.pid
#This is the command to be run, give the full pathname
DAEMON=/usr/bin/indigo-reposync

case "$1" in
  start)
        echo -n "Starting daemon: "$NAME
	$DAEMON start
        echo "."
	;;
  stop)
        echo -n "Stopping daemon: "$NAME
	$DAEMON stop
        echo "."
	;;
  restart)
        echo -n "Restarting daemon: "$NAME
	$DAEMON stop
	$DAEMON start
	echo "."
	;;

  *)
	echo "Usage: "$1" {start|stop|restart}"
	exit 1
esac

exit 0

